# Generated by Django 3.2.6 on 2021-08-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_license'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='license',
            table='lic',
        ),
    ]
